/*
 * File: app/view/com/oocl/ir4/training/TrainingViewPort.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Training.view.com.oocl.ir4.training.TrainingViewPort', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.button.Button'
    ],

    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    region: 'north',
                    height: 150,
                    bodyPadding: 10,
                    title: 'Find Facility',
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            id: 'facilityCode',
                            itemId: 'facilityCode',
                            fieldLabel: 'Facility Code'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            items: [
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'codeFcil',
                                    text: 'Search',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonClick,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
        var facilityCode = null;
        facilityCode = Ext.getCmp("facilityCode");
        console.log("Facility Code "  + facilityCode);
        console.log("Facility Code "  , facilityCode);

        var codeFacil = null;
        codeFacil = Ext.ComponentQuery.query("[itemId='codeFacil'']");
        console.log("Facility Code by Component Query", codeFacil)
    }

});